name: 🚀 Deploy Laravel (cPanel Safe)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build assets
        run: |
          npm install
          npm run build

      - name: FTP Deploy (FTPS, safe excludes)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          security: loose
          timeout: 120000
          local-dir: ./
          server-dir: /home/qoittgkw/gallery-app/
          exclude: |
            **/.git**
            **/.github/**
            **/.vscode/**
            **/.idea/**
            **/.DS_Store
            **/*.log
            **/*.sql
            **/*.zip
            **/*.tar.gz
            **/node_modules/**
            **/vendor/**              # biarkan vendor di server apa adanya
            **/tests/**
            **/storage/**             # jangan sentuh storage server
            **/public/storage/**      # jaga symlink storage di public
            **/.env                   # jangan pernah upload .env
            **/.env.*                 # semua varian .env.* juga skip

    #   - name: Clear Laravel Cache
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.FTP_SERVER }}
    #       username: ${{ secrets.FTP_USERNAME }}
    #       password: ${{ secrets.FTP_PASSWORD }}
    #       port: ${{ secrets.FTP_PORT }}
    #       script: |
    #         cd /home/qoittgkw/gallery-app
    #         php artisan view:clear
    #         php artisan route:clear
    #         php artisan config:clear
    #         php artisan cache:clear
